Enable disable floats
bytecodealliance/wasmparser pull request #121
Opened 2019-08-08 12:01 UTC by YaronWittenstein

Hi @yurydelendik 

I've added a new operator config option called `enable_floats` (defaults to `true`) under the `OperatorValidatorConfig`.

I believe this PR will be very useful for most (if not all) Blockchain projects using `wasm` for running smart-contracts.

Blockchain project using wasm avoid floats in order to stay deterministic across different hardware / operating-systems.

Thank you!
   Yaron

2019-08-08 13:44 UTC, sunfishcode commented
This patch appears to disable float operators, but not float types, for example in function signatures, locals, or globals. Is that intended?

If you do intend to disable float types, disabling float operators would then be unnecessary and the patch could be simpler, because it's not possible to use float operators if there are no float types (except in unreachable code, but there they can be ignored).

Also, while I don't object to the patch, I do want to mention for what it's worth that WebAssembly's floating-point is deterministic in all respects except for NaN bits. Some platforms tolerate some floating-point rounding nondeterminism, but [WebAssembly does not](https://github.com/WebAssembly/testsuite/blob/master/float_misc.wast#L122).

2019-08-08 13:56 UTC, YaronWittenstein commented
@sunfishcode Hi!

Basically, I wanted to make sure no floating operators will appear in the code.
I guess that floating types could still appear. I wasn't sure how it the best way to disable the float types in the source code.

Thank you for the clarification regarding the deterministic nature of floats in wasm.
Nonetheless, I know that in my company we'd like to avoid them feature-wise (and as said, I believe more Blockchain projects will find that feature relevant).

2019-08-08 14:43 UTC, yurydelendik commented
> I believe more Blockchain projects will find that feature relevant

Except float, which features will be beneficial? The reason why I'm asking is that in might be beneficial to move it to the feature level and use `#[cfg(feature = ` for blockchain-related subset. Perhaps even for deterministic stuff two?

2019-08-08 15:46 UTC, YaronWittenstein commented
I think that having `#[cfg(feature = deterministic)]` could be interesting.
Right now, I don't have anything else that stops me besides avoiding floats.

On the other hand, I guess that different Blockchain projects will have differentiations regarding what they would like to have. I'm afraid this feature might be a bit immature right now... (IMHO)

Personally, I love the freedom to enable/disable each feature in isolation as it's right now (and there aren't many flags right now).

Thank you!

2019-08-21 13:14 UTC, YaronWittenstein commented
Hi @yurydelendik @sunfishcode 

I'll need this feature pretty soon, and I'd rather not work with a forked version.
Please let me know if there's anything I can help with, in order to push this feature/similar forward.

Thank you!

2019-08-21 13:26 UTC, yurydelendik requested changes
Let's do this while we thinking about effect on the code base and future of the deterministic instructions subset:

- Add `deterministic` feature, and disable it by default
- Change `enable_floats` to `deterministic_only` and move it inside `cfg()`
   * P.S. feature is disabled though default can be assigned to `true`
- Change `check_floats_enabled` to `check_non_deterministic_enabled` (and add `cfg()` there too)
- Make tests available with deterministic feature only, maybe add `cargo test --features deterministic ..` to the test-all.sh

2019-08-21 15:28 UTC, sunfishcode commented
Another feature with nondeterminism is shared memory.

2019-08-21 15:28 UTC, YaronWittenstein commented
Hi @yurydelendik 
I've made changes according to your guidance
Thank you!

2019-08-21 15:35 UTC, YaronWittenstein commented
@yurydelendik my tests failed, I'm checking why.

@sunfishcode I'll need to add the `deterministic` feature to `check_shared_memarg_wo_align` too right?

2019-08-21 15:50 UTC, sunfishcode commented
@YaronWittenstein I believe `check_shared_memarg_wo_align` is only called when `check_threads_enabled` returns true, so it shouldn't need an extra check.

2019-08-21 16:09 UTC, YaronWittenstein commented
tests pass now :)

2019-08-21 16:17 UTC, yurydelendik approved these changes
looks good with error message fix.

I wonder if we need explicitly enable/disable shared memory access via this feature as well. But we can iterate over this later.

2019-08-21 16:17 UTC, yurydelendik commented on src/operators_validator.rs
> +            return Err("floats support is not enabled");
nit: fix error message

2019-08-21 16:30 UTC, YaronWittenstein commented on src/operators_validator.rs
> +            return Err("floats support is not enabled");
fixed

2019-08-21 16:30 UTC, YaronWittenstein commented on src/operators_validator.rs
> +            return Err("floats support is not enabled");
Does this change require a version bump?

2019-08-21 16:32 UTC, yurydelendik commented on src/operators_validator.rs
> +            return Err("floats support is not enabled");
it does -- I'll do it

2019-08-21 18:55 UTC, merged

2019-08-21 18:56 UTC, yurydelendik commented
Thank you for the patch.

2019-08-21 18:57 UTC, YaronWittenstein commented
Thank you!