Add cargo-fuzz related files.
bytecodealliance/wasmparser pull request #23
Opened 2017-06-23 02:33 UTC by frewsxcv

2017-06-23 02:39 UTC, frewsxcv commented
To use this:

`cargo install cargo-fuzz`

`cargo fuzz run <fuzz target name>`, in this case `cargo fuzz run parse`

if you want to add some files to use as seeds for the fuzzer, add them to `fuzz/corpus/parse/`. i recommend adding all the files from `test/` into there and then rerunning

2017-06-23 13:20 UTC, yurydelendik requested changes
Thank you.

I don't think we want to package fuzz into the crate package. Can you add exclude entry to the main Cargo.toml?

Can you squash commits? There is no reason to have "touch up" commits.

Please create a local README.md with the same instructions you provided in the PR comments. I was not able to run by following those instructions:

```
fuzz yury$ cargo fuzz run parse
error: could not decode the manifest file at "wasmparser.rs/wasmparser/Cargo.toml"
  caused by: redefinition of table `package` for key `package` at line 23
```

2017-06-23 13:20 UTC, yurydelendik commented on fuzz/.gitignore
> +
remove empty line

2017-06-23 13:20 UTC, yurydelendik commented on fuzz/Cargo.toml
> +authors = ["Automatically generated"]
nit: fix author name

2017-06-23 15:28 UTC, frewsxcv commented
> Can you squash commits? There is no reason to have "touch up" commits.

https://github.com/blog/2141-squash-your-commits

> Please create a local README.md with the same instructions you provided in the PR comments. I was not able to run by following those instructions:

Which directory did you run the command from? You should run it from the repository root, not from within the `fuzz/` directory.

2017-06-23 15:41 UTC, yurydelendik commented
> https://github.com/blog/2141-squash-your-commits

Personally I'm trying not to do that: it removes signed commit verification and modifies origin of commit. I'm doing squashing only if contributors cannot to it himself. Would you like to squash it for you?

2017-06-23 15:49 UTC, yurydelendik commented
> You should run it from the repository root, not from within the fuzz/ directory.

Different error when run from repo's dir: https://gist.github.com/yurydelendik/c59534507de07801fed90865854874e9

2017-06-23 15:50 UTC, frewsxcv commented
Ah, you'll need to run nightly Rust for this. `rustup default nightly` if you're using rustup. I can add that to the README when I get around to it.

2017-06-23 15:54 UTC, yurydelendik commented
>  I can add that to the README when I get around to it.

Yes, please. Can you add fuzzing section to the README?

2017-06-23 15:54 UTC, yurydelendik approved these changes

2017-06-25 00:57 UTC, frewsxcv commented
Added a brief section to the README and squashed.

2017-07-03 14:32 UTC, merged

2017-07-03 14:32 UTC, yurydelendik commented
Thank you for the patch