Add benchmark
bytecodealliance/wasmparser pull request #95
Opened 2019-03-12 23:38 UTC by iamonuwa

Fixes #8

2019-03-12 23:38 UTC, iamonuwa commented
@mbebenita @yurydelendik please review

2019-03-13 14:22 UTC, yurydelendik reviewed
When I add sleep call to the read_file_data(), I see changes in the benchmark performance run -- any I/O shall not affect test results.

2019-03-13 14:22 UTC, yurydelendik commented on benches/benchmark.rs
> +    println!("Parsing {:?}", path);
can you remove this line

2019-03-13 14:53 UTC, iamonuwa commented on benches/benchmark.rs
> +    println!("Parsing {:?}", path);
Okay

2019-03-13 14:54 UTC, iamonuwa commented
> When I add sleep call to the read_file_data(), I see changes in the benchmark performance run -- any I/O shall not affect test results.

Can you elaborate on this please?

2019-03-13 14:59 UTC, yurydelendik commented
> Can you elaborate on this please?

Benchmark test need to measure performance of the Parser/ValidatingParser. Looks like the solution is measuring the performance of the read_file_data function as well, which is not part of the Parser, and definitely skews the results. As I mentioned in [the comment](https://github.com/yurydelendik/wasmparser.rs/issues/8#issuecomment-471999627), to avoid that you may need to load/cache all wasm data prior running the testing.

2019-03-13 15:08 UTC, iamonuwa commented
> > Can you elaborate on this please?
> 
> Benchmark test need to measure performance of the Parser/ValidatingParser. Looks like the solution is measuring the performance of the read_file_data function as well, which is not part of the Parser, and definitely skews the results. As I mentioned in [the comment](https://github.com/yurydelendik/wasmparser.rs/issues/8#issuecomment-471999627), to avoid that you may need to load/cache all wasm data prior running the testing.

Any preferred option for in-memory cache?

2019-03-13 15:09 UTC, yurydelendik commented
> Any preferred option for in-memory cache?

`std::vec::Vec<>` shall work fine.

2019-03-13 15:26 UTC, iamonuwa commented
Alright, I'll work with this now

2019-03-13 16:45 UTC, iamonuwa commented
@yurydelendik If I get you correctly, the benchmark should run for each of the tests? Right

2019-03-13 17:02 UTC, yurydelendik commented
>  If I get you correctly, the benchmark should run for each of the tests? Right

I don't understand the question. But what I was saying that performance of read_file_data (which has I/O operations) shall not influence results of the benchmark test results. #8 is not clear on that, but bench shall test performances of the Parser (and ValidatingParser), and we want to have most of its functionality covered during test run. That said, the enough tests shall be executed during bench to get performance coverage of most of the code base. (The performances of reading files from disk is irrelevant)

2019-03-13 17:04 UTC, iamonuwa commented
Do you have a link or guide that can explain how to remove the additional functions? This is how I normally write benchmarks

2019-03-13 17:08 UTC, iamonuwa commented
This is how the output looks like.
![image](https://user-images.githubusercontent.com/6551094/54299281-dd448680-45ba-11e9-8add-d879c940ac30.png)

I had to move the data outside the bench_function

2019-03-13 17:53 UTC, iamonuwa commented
Can you confirm?

2019-03-13 18:08 UTC, yurydelendik commented
Tested again: still a problem

```
Yurys-Workspace:wasmparser yury$ cargo bench
    Finished release [optimized] target(s) in 0.18s
     Running target/release/deps/wasmparser-b27d87a6221dce03

running 7 tests
test tests::simple_tests::default_read ... ignored
test tests::simple_tests::default_read_with_input ... ignored
test tests::simple_tests::it_works ... ignored
test tests::simple_tests::skipping ... ignored
test tests::simple_tests::validator_fails ... ignored
test tests::simple_tests::validator_not_fails ... ignored
test validator::test_validate ... ignored

test result: ok. 0 passed; 0 failed; 7 ignored; 0 measured; 0 filtered out

     Running target/release/deps/benchmark-97097cd7f0076b61
Gnuplot not found, disabling plotting
it works benchmark      time:   [115.85 ns 118.91 ns 123.55 ns]                               
Found 8 outliers among 100 measurements (8.00%)
  8 (8.00%) high severe

validator no fails benchmark                                                                            
                        time:   [251.47 ns 256.82 ns 263.57 ns]
Found 9 outliers among 100 measurements (9.00%)
  2 (2.00%) high mild
  7 (7.00%) high severe

Gnuplot not found, disabling plotting
Yurys-Workspace:wasmparser yury$ vi benches/benchmark.rs 
Yurys-Workspace:wasmparser yury$ git diff
diff --git a/benches/benchmark.rs b/benches/benchmark.rs
index b1d600c..39282d0 100644
--- a/benches/benchmark.rs
+++ b/benches/benchmark.rs
@@ -1,6 +1,7 @@
 pub fn read_file_data(path: &PathBuf) -> Vec<u8> {
     let mut data = Vec::new();
     let mut f = File::open(path).ok().unwrap();
+::std::thread::sleep(::std::time::Duration::from_micros(50));
     f.read_to_end(&mut data).unwrap();
     data
 }
Yurys-Workspace:wasmparser yury$ cargo bench
   Compiling wasmparser v0.29.2 (/Users/yury/Work/junk/wasmparser.rs/wasmparser)
    Finished release [optimized] target(s) in 1.02s
     Running target/release/deps/wasmparser-b27d87a6221dce03

running 7 tests
test tests::simple_tests::default_read ... ignored
test tests::simple_tests::default_read_with_input ... ignored
test tests::simple_tests::it_works ... ignored
test tests::simple_tests::skipping ... ignored
test tests::simple_tests::validator_fails ... ignored
test tests::simple_tests::validator_not_fails ... ignored
test validator::test_validate ... ignored

test result: ok. 0 passed; 0 failed; 7 ignored; 0 measured; 0 filtered out

     Running target/release/deps/benchmark-97097cd7f0076b61
Gnuplot not found, disabling plotting
it works benchmark      time:   [232.70 ns 260.96 ns 290.36 ns]                               
                        change: [+124.96% +143.21% +160.95%] (p = 0.00 < 0.05)
                        Performance has regressed.

validator no fails benchmark                                                                            
                        time:   [308.30 ns 347.51 ns 393.16 ns]
                        change: [+22.541% +31.809% +43.493%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 12 outliers among 100 measurements (12.00%)
  2 (2.00%) high mild
  10 (10.00%) high severe

Gnuplot not found, disabling plotting
```

Notice the performance "regressed" because of in slow down in reading of the file from disk.

2019-03-13 18:19 UTC, yurydelendik commented
> I had to move the data outside the bench_function

Did you commit this code?

2019-03-13 19:14 UTC, iamonuwa commented
Apologies, pushing new update now

2019-03-13 19:22 UTC, yurydelendik requested changes

2019-03-13 19:22 UTC, yurydelendik commented on benches/benchmark.rs
> +        c.bench_function("it works benchmark", move |b| {
(here and below) move bench_function call out of this loop, store loaded file in the vector, add second loop in the closure and iterate on loaded files.

2019-03-14 12:58 UTC, yurydelendik commented on benches/benchmark.rs
> +    let mut data: Vec<u8> = vec![];
Use Vec<Vec<u8>> here

2019-03-14 17:26 UTC, iamonuwa commented on benches/benchmark.rs
> +    let mut data: Vec<u8> = vec![];
Using this causes failure on the bench

![image](https://user-images.githubusercontent.com/6551094/54377999-a471e380-4686-11e9-9ae8-ddc8bc5bcc52.png)

2019-03-14 17:31 UTC, yurydelendik commented on benches/benchmark.rs
> +    let mut data: Vec<u8> = vec![];
See https://github.com/yurydelendik/wasmparser.rs/pull/95#discussion_r265293414

> ... store loaded file in the vector, add second loop in the closure and iterate on loaded files.

2019-03-15 06:37 UTC, iamonuwa commented
@yurydelendik please review

2019-03-15 13:10 UTC, yurydelendik commented on benches/benchmark.rs
> +    for d in data {
As pointed in https://github.com/yurydelendik/wasmparser.rs/pull/95/files#r265293414
> add second loop in the closure and iterate on loaded files.

Could you move this loop *inside* the bench_function ?

2019-03-15 14:46 UTC, iamonuwa commented on benches/benchmark.rs
> +    for d in data {
Yeah sure!

2019-03-15 14:52 UTC, iamonuwa commented
@yurydelendik please review

2019-03-15 14:58 UTC, yurydelendik approved these changes

2019-03-15 14:58 UTC, merged

2019-03-15 15:00 UTC, yurydelendik commented
Thank you for the patch

2019-03-15 15:12 UTC, iamonuwa commented
Thank you for supporting!